version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run
          command: node index.js

workflows:
  version: 2
  scheduled-workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/ # Ignore branch commits
    triggers:
      schedule:
        - cron: "0 10 * * THU" ## Runs at 10:00, only on Thursday
        - cron: "30 10 * * SUN" # Runs at 10:30, only on Sunday
  manual-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/ # Include all branches
          when: manual
