name: Send vocabularies everyweek (11AM sunday)
on:
  schedule:
    - cron: "0 10 * * THU" ## Runs at 10:00, only on Thursday
    - cron: "30 10 * * SUN" # Runs at 10:30, only on Sunday
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: sending email
        env:
          SENDING_EMAIL: ${{ secrets.SENDING_EMAIL }}
          SENDING_PASSWORD: ${{ secrets.SENDING_PASSWORD }}
          DESTINATION_EMAIL: ${{ secrets.DESTINATION_EMAIL }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        run: node index.js
